/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class N$16
    extends Token {

  N$16(String text, int line, int pos) {
    super(text, line, pos);
  }

  @Override
  public Type getType() {
    return Type.TAnonymous;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_$16;
  }
}
