/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NArgs_None
    extends NArgs {

  private final int line;
  private final int pos;

  @Override
  public void apply(Walker walker) {
    walker.inArgs_None(this);
    walker.caseArgs_None(this);
    walker.outArgs_None(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
  }

  public NArgs_None(int line, int pos) {
    this.line = line;
    this.pos = pos;
  }

  @Override
  public Type getType() {
    return Type.T_Args_None;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Args;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Args_None;
  }
}
