/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NArgs_Many
    extends NArgs {

  private final int line;
  private final int pos;
  private final NArg eArg;
  private final NCommaArgs eCommaArgs;

  @Override
  public void apply(Walker walker) {
    walker.inArgs_Many(this);
    walker.caseArgs_Many(this);
    walker.outArgs_Many(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eArg.apply(walker);
    this.eCommaArgs.apply(walker);
  }

  public NArgs_Many(int line, int pos, NArg pArg, NCommaArgs pCommaArgs) {
    this.line = line;
    this.pos = pos;
    this.eArg = pArg;
    this.eCommaArgs = pCommaArgs;
  }

  @Override
  public Type getType() {
    return Type.T_Args_Many;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Args;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Args_Many;
  }

  public NArg get_Arg() {
    return this.eArg;
  }

  public NCommaArgs get_CommaArgs() {
    return this.eCommaArgs;
  }

  NArg internalGetArg() {
    return this.eArg;
  }

  NCommaArgs internalGetCommaArgs() {
    return this.eCommaArgs;
  }
}
