/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class NArgs_$1
    extends NArgs {

  private final int line;
  private final int pos;
  private final NArg eArg;
  private final NCommaArgs eCommaArgs;

  @Override
  public void apply(Walker walker) {
    walker.defaultIn(this);
    walker.defaultCase(this);
    walker.defaultOut(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eArg.apply(walker);
    this.eCommaArgs.apply(walker);
  }

  NArgs_$1(int line, int pos, NArg pArg, NCommaArgs pCommaArgs) {
    this.line = line;
    this.pos = pos;
    this.eArg = pArg;
    this.eCommaArgs = pCommaArgs;
  }

  @Override
  public Type getType() {
    return Type.TAnonymous;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Args;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Args_$1;
  }

  NArg internalGetArg() {
    return this.eArg;
  }

  NCommaArgs internalGetCommaArgs() {
    return this.eCommaArgs;
  }
}
