/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NCommaArgs_None
    extends NCommaArgs {

  private final int line;
  private final int pos;

  @Override
  public void apply(Walker walker) {
    walker.inCommaArgs_None(this);
    walker.caseCommaArgs_None(this);
    walker.outCommaArgs_None(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
  }

  public NCommaArgs_None(int line, int pos) {
    this.line = line;
    this.pos = pos;
  }

  @Override
  public Type getType() {
    return Type.T_CommaArgs_None;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_CommaArgs;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_CommaArgs_None;
  }
}
