/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NCommaArgs_Many
    extends NCommaArgs {

  private final int line;
  private final int pos;
  private final NCommaArgs eCommaArgs;
  private final N$2 eComma;
  private final NArg eArg;

  @Override
  public void apply(Walker walker) {
    walker.inCommaArgs_Many(this);
    walker.caseCommaArgs_Many(this);
    walker.outCommaArgs_Many(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eCommaArgs.apply(walker);
    this.eComma.apply(walker);
    this.eArg.apply(walker);
  }

  NCommaArgs_Many(int line, int pos, NCommaArgs pCommaArgs, N$2 pComma, NArg pArg) {
    this.line = line;
    this.pos = pos;
    this.eCommaArgs = pCommaArgs;
    this.eComma = pComma;
    this.eArg = pArg;
  }

  @Override
  public Type getType() {
    return Type.T_CommaArgs_Many;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_CommaArgs;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_CommaArgs_Many;
  }

  public NCommaArgs get_CommaArgs() {
    return this.eCommaArgs;
  }

  public Token get_Comma() {
    return this.eComma;
  }

  public NArg get_Arg() {
    return this.eArg;
  }

  NCommaArgs internalGetCommaArgs() {
    return this.eCommaArgs;
  }

  N$2 internalGetComma() {
    return this.eComma;
  }

  NArg internalGetArg() {
    return this.eArg;
  }
}
