/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class NCommaArgs_$1
    extends NCommaArgs {

  private final int line;
  private final int pos;
  private final NCommaArgs eCommaArgs;
  private final N$2 eComma;
  private final NArg eArg;

  @Override
  public void apply(Walker walker) {
    walker.defaultIn(this);
    walker.defaultCase(this);
    walker.defaultOut(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eCommaArgs.apply(walker);
    this.eComma.apply(walker);
    this.eArg.apply(walker);
  }

  NCommaArgs_$1(int line, int pos, NCommaArgs pCommaArgs, N$2 pComma, NArg pArg) {
    this.line = line;
    this.pos = pos;
    this.eCommaArgs = pCommaArgs;
    this.eComma = pComma;
    this.eArg = pArg;
  }

  @Override
  public Type getType() {
    return Type.TAnonymous;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_CommaArgs;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_CommaArgs_$1;
  }

  NCommaArgs internalGetCommaArgs() {
    return this.eCommaArgs;
  }

  N$2 internalGetComma() {
    return this.eComma;
  }

  NArg internalGetArg() {
    return this.eArg;
  }
}
