/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class NCommaParams_$1
    extends NCommaParams {

  private final int line;
  private final int pos;
  private final NCommaParams eCommaParams;
  private final N$2 eComma;
  private final NParam eParam;

  @Override
  public void apply(Walker walker) {
    walker.defaultIn(this);
    walker.defaultCase(this);
    walker.defaultOut(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eCommaParams.apply(walker);
    this.eComma.apply(walker);
    this.eParam.apply(walker);
  }

  NCommaParams_$1(int line, int pos, NCommaParams pCommaParams, N$2 pComma, NParam pParam) {
    this.line = line;
    this.pos = pos;
    this.eCommaParams = pCommaParams;
    this.eComma = pComma;
    this.eParam = pParam;
  }

  @Override
  public Type getType() {
    return Type.TAnonymous;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_CommaParams;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_CommaParams_$1;
  }

  NCommaParams internalGetCommaParams() {
    return this.eCommaParams;
  }

  N$2 internalGetComma() {
    return this.eComma;
  }

  NParam internalGetParam() {
    return this.eParam;
  }
}
