/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NCommaParams_None
    extends NCommaParams {

  private final int line;
  private final int pos;

  @Override
  public void apply(Walker walker) {
    walker.inCommaParams_None(this);
    walker.caseCommaParams_None(this);
    walker.outCommaParams_None(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
  }

  public NCommaParams_None(int line, int pos) {
    this.line = line;
    this.pos = pos;
  }

  @Override
  public Type getType() {
    return Type.T_CommaParams_None;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_CommaParams;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_CommaParams_None;
  }
}
