/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NCommaParams_Many
    extends NCommaParams {

  private final int line;
  private final int pos;
  private final NCommaParams eCommaParams;
  private final N$2 eComma;
  private final NParam eParam;

  @Override
  public void apply(Walker walker) {
    walker.inCommaParams_Many(this);
    walker.caseCommaParams_Many(this);
    walker.outCommaParams_Many(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eCommaParams.apply(walker);
    this.eComma.apply(walker);
    this.eParam.apply(walker);
  }

  NCommaParams_Many(int line, int pos, NCommaParams pCommaParams, N$2 pComma, NParam pParam) {
    this.line = line;
    this.pos = pos;
    this.eCommaParams = pCommaParams;
    this.eComma = pComma;
    this.eParam = pParam;
  }

  @Override
  public Type getType() {
    return Type.T_CommaParams_Many;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_CommaParams;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_CommaParams_Many;
  }

  public NCommaParams get_CommaParams() {
    return this.eCommaParams;
  }

  public Token get_Comma() {
    return this.eComma;
  }

  public NParam get_Param() {
    return this.eParam;
  }

  NCommaParams internalGetCommaParams() {
    return this.eCommaParams;
  }

  N$2 internalGetComma() {
    return this.eComma;
  }

  NParam internalGetParam() {
    return this.eParam;
  }
}
