/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NExp_Neg
    extends NExp {

  private final int line;
  private final int pos;
  private final N$22 eOp;
  private final NTerm eTerm;

  @Override
  public void apply(Walker walker) {
    walker.inExp_Neg(this);
    walker.caseExp_Neg(this);
    walker.outExp_Neg(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eOp.apply(walker);
    this.eTerm.apply(walker);
  }

  NExp_Neg(int line, int pos, N$22 pOp, NTerm pTerm) {
    this.line = line;
    this.pos = pos;
    this.eOp = pOp;
    this.eTerm = pTerm;
  }

  @Override
  public Type getType() {
    return Type.T_Exp_Neg;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Exp;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Exp_Neg;
  }

  public Token get_Op() {
    return this.eOp;
  }

  public NTerm get_Term() {
    return this.eTerm;
  }

  N$22 internalGetOp() {
    return this.eOp;
  }

  NTerm internalGetTerm() {
    return this.eTerm;
  }
}
