/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class NFuns_$1
    extends NFuns {

  private final int line;
  private final int pos;
  private final NFuns eFuns;
  private final NFun eFun;

  @Override
  public void apply(Walker walker) {
    walker.defaultIn(this);
    walker.defaultCase(this);
    walker.defaultOut(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eFuns.apply(walker);
    this.eFun.apply(walker);
  }

  NFuns_$1(int line, int pos, NFuns pFuns, NFun pFun) {
    this.line = line;
    this.pos = pos;
    this.eFuns = pFuns;
    this.eFun = pFun;
  }

  @Override
  public Type getType() {
    return Type.TAnonymous;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Funs;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Funs_$1;
  }

  NFuns internalGetFuns() {
    return this.eFuns;
  }

  NFun internalGetFun() {
    return this.eFun;
  }
}
