/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NFuns_Many
    extends NFuns {

  private final int line;
  private final int pos;
  private final NFuns eFuns;
  private final NFun eFun;

  @Override
  public void apply(Walker walker) {
    walker.inFuns_Many(this);
    walker.caseFuns_Many(this);
    walker.outFuns_Many(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eFuns.apply(walker);
    this.eFun.apply(walker);
  }

  public NFuns_Many(int line, int pos, NFuns pFuns, NFun pFun) {
    this.line = line;
    this.pos = pos;
    this.eFuns = pFuns;
    this.eFun = pFun;
  }

  @Override
  public Type getType() {
    return Type.T_Funs_Many;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Funs;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Funs_Many;
  }

  public NFuns get_Funs() {
    return this.eFuns;
  }

  public NFun get_Fun() {
    return this.eFun;
  }

  NFuns internalGetFuns() {
    return this.eFuns;
  }

  NFun internalGetFun() {
    return this.eFun;
  }
}
