/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NNum
    extends Token {

  public NNum(String text, int line, int pos) {
    super(text, line, pos);
  }

  @Override
  public Type getType() {
    return Type.T_Num;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Num;
  }

  @Override
  public void apply(Walker walker) {
    walker.inNum(this);
    walker.caseNum(this);
    walker.outNum(this);
  }
}
