/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class NOptExp_$1
    extends NOptExp {

  private final int line;
  private final int pos;
  private final NExp eExp;

  @Override
  public void apply(Walker walker) {
    walker.defaultIn(this);
    walker.defaultCase(this);
    walker.defaultOut(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eExp.apply(walker);
  }

  NOptExp_$1(int line, int pos, NExp pExp) {
    this.line = line;
    this.pos = pos;
    this.eExp = pExp;
  }

  @Override
  public Type getType() {
    return Type.TAnonymous;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_OptExp;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_OptExp_$1;
  }

  NExp internalGetExp() {
    return this.eExp;
  }
}
