/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NOptExp_None
    extends NOptExp {

  private final int line;
  private final int pos;

  @Override
  public void apply(Walker walker) {
    walker.inOptExp_None(this);
    walker.caseOptExp_None(this);
    walker.outOptExp_None(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
  }

  public NOptExp_None(int line, int pos) {
    this.line = line;
    this.pos = pos;
  }

  @Override
  public Type getType() {
    return Type.T_OptExp_None;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_OptExp;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_OptExp_None;
  }
}
