/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class NParams_$1
    extends NParams {

  private final int line;
  private final int pos;
  private final NParam eParam;
  private final NCommaParams eCommaParams;

  @Override
  public void apply(Walker walker) {
    walker.defaultIn(this);
    walker.defaultCase(this);
    walker.defaultOut(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eParam.apply(walker);
    this.eCommaParams.apply(walker);
  }

  NParams_$1(int line, int pos, NParam pParam, NCommaParams pCommaParams) {
    this.line = line;
    this.pos = pos;
    this.eParam = pParam;
    this.eCommaParams = pCommaParams;
  }

  @Override
  public Type getType() {
    return Type.TAnonymous;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Params;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Params_$1;
  }

  NParam internalGetParam() {
    return this.eParam;
  }

  NCommaParams internalGetCommaParams() {
    return this.eCommaParams;
  }
}
