/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NParam
    extends Node {

  private final int line;
  private final int pos;
  private final NType eType;
  private final NId eId;

  @Override
  public void apply(Walker walker) {
    walker.inParam(this);
    walker.caseParam(this);
    walker.outParam(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eType.apply(walker);
    this.eId.apply(walker);
  }

  public NParam(int line, int pos, NType pType, NId pId) {
    this.line = line;
    this.pos = pos;
    this.eType = pType;
    this.eId = pId;
  }

  @Override
  public Type getType() {
    return Type.T_Param;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Param;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Param;
  }

  public NType get_Type() {
    return this.eType;
  }

  public NId get_Id() {
    return this.eId;
  }

  NType internalGetType() {
    return this.eType;
  }

  NId internalGetId() {
    return this.eId;
  }
}
