/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NParams_None
    extends NParams {

  private final int line;
  private final int pos;

  @Override
  public void apply(Walker walker) {
    walker.inParams_None(this);
    walker.caseParams_None(this);
    walker.outParams_None(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
  }

  public NParams_None(int line, int pos) {
    this.line = line;
    this.pos = pos;
  }

  @Override
  public Type getType() {
    return Type.T_Params_None;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Params;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Params_None;
  }
}
