/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NParams_Many
    extends NParams {

  private final int line;
  private final int pos;
  private final NParam eParam;
  private final NCommaParams eCommaParams;

  @Override
  public void apply(Walker walker) {
    walker.inParams_Many(this);
    walker.caseParams_Many(this);
    walker.outParams_Many(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eParam.apply(walker);
    this.eCommaParams.apply(walker);
  }

  public NParams_Many(int line, int pos, NParam pParam, NCommaParams pCommaParams) {
    this.line = line;
    this.pos = pos;
    this.eParam = pParam;
    this.eCommaParams = pCommaParams;
  }

  @Override
  public Type getType() {
    return Type.T_Params_Many;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Params;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Params_Many;
  }

  public NParam get_Param() {
    return this.eParam;
  }

  public NCommaParams get_CommaParams() {
    return this.eCommaParams;
  }

  NParam internalGetParam() {
    return this.eParam;
  }

  NCommaParams internalGetCommaParams() {
    return this.eCommaParams;
  }
}
