/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NStmt_Call
    extends NStmt {

  private final int line;
  private final int pos;
  private final NId eId;
  private final N$0 eLPar;
  private final NArgs eArgs;
  private final N$1 e$1;
  private final N$6 e$6;

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Call(this);
    walker.caseStmt_Call(this);
    walker.outStmt_Call(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eId.apply(walker);
    this.eLPar.apply(walker);
    this.eArgs.apply(walker);
    this.e$1.apply(walker);
    this.e$6.apply(walker);
  }

  NStmt_Call(int line, int pos, NId pId, N$0 pLPar, NArgs pArgs, N$1 p$1, N$6 p$6) {
    this.line = line;
    this.pos = pos;
    this.eId = pId;
    this.eLPar = pLPar;
    this.eArgs = pArgs;
    this.e$1 = p$1;
    this.e$6 = p$6;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Call;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Call;
  }

  public NId get_Id() {
    return this.eId;
  }

  public Token get_LPar() {
    return this.eLPar;
  }

  public NArgs get_Args() {
    return this.eArgs;
  }

  NId internalGetId() {
    return this.eId;
  }

  N$0 internalGetLPar() {
    return this.eLPar;
  }

  NArgs internalGetArgs() {
    return this.eArgs;
  }

  N$1 internalGet$1() {
    return this.e$1;
  }

  N$6 internalGet$6() {
    return this.e$6;
  }
}
