/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NStmt_Return
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$13 eKeyword;
  private final NOptExp eOptExp;
  private final N$6 e$6;

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Return(this);
    walker.caseStmt_Return(this);
    walker.outStmt_Return(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eKeyword.apply(walker);
    this.eOptExp.apply(walker);
    this.e$6.apply(walker);
  }

  NStmt_Return(int line, int pos, N$13 pKeyword, NOptExp pOptExp, N$6 p$6) {
    this.line = line;
    this.pos = pos;
    this.eKeyword = pKeyword;
    this.eOptExp = pOptExp;
    this.e$6 = p$6;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Return;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Return;
  }

  public Token get_Keyword() {
    return this.eKeyword;
  }

  public NOptExp get_OptExp() {
    return this.eOptExp;
  }

  N$13 internalGetKeyword() {
    return this.eKeyword;
  }

  NOptExp internalGetOptExp() {
    return this.eOptExp;
  }

  N$6 internalGet$6() {
    return this.e$6;
  }
}
