/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NStmts_None
    extends NStmts {

  private final int line;
  private final int pos;

  @Override
  public void apply(Walker walker) {
    walker.inStmts_None(this);
    walker.caseStmts_None(this);
    walker.outStmts_None(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
  }

  public NStmts_None(int line, int pos) {
    this.line = line;
    this.pos = pos;
  }

  @Override
  public Type getType() {
    return Type.T_Stmts_None;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmts;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmts_None;
  }
}
