/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NStmt_ArrayAssign
    extends NStmt {

  private final int line;
  private final int pos;
  private final NId eId;
  private final N$7 eLBracket;
  private final NExp eIndex;
  private final N$8 e$8;
  private final N$5 eOp;
  private final NExp eExp;
  private final N$6 e$6;

  @Override
  public void apply(Walker walker) {
    walker.inStmt_ArrayAssign(this);
    walker.caseStmt_ArrayAssign(this);
    walker.outStmt_ArrayAssign(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eId.apply(walker);
    this.eLBracket.apply(walker);
    this.eIndex.apply(walker);
    this.e$8.apply(walker);
    this.eOp.apply(walker);
    this.eExp.apply(walker);
    this.e$6.apply(walker);
  }

  NStmt_ArrayAssign(int line, int pos, NId pId, N$7 pLBracket, NExp pIndex, N$8 p$8, N$5 pOp, NExp pExp, N$6 p$6) {
    this.line = line;
    this.pos = pos;
    this.eId = pId;
    this.eLBracket = pLBracket;
    this.eIndex = pIndex;
    this.e$8 = p$8;
    this.eOp = pOp;
    this.eExp = pExp;
    this.e$6 = p$6;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_ArrayAssign;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_ArrayAssign;
  }

  public NId get_Id() {
    return this.eId;
  }

  public Token get_LBracket() {
    return this.eLBracket;
  }

  public NExp get_Index() {
    return this.eIndex;
  }

  public Token get_Op() {
    return this.eOp;
  }

  public NExp get_Exp() {
    return this.eExp;
  }

  NId internalGetId() {
    return this.eId;
  }

  N$7 internalGetLBracket() {
    return this.eLBracket;
  }

  NExp internalGetIndex() {
    return this.eIndex;
  }

  N$8 internalGet$8() {
    return this.e$8;
  }

  N$5 internalGetOp() {
    return this.eOp;
  }

  NExp internalGetExp() {
    return this.eExp;
  }

  N$6 internalGet$6() {
    return this.e$6;
  }
}
