/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NStmt_Decl
    extends NStmt {

  private final int line;
  private final int pos;
  private final NType eType;
  private final NId eId;
  private final N$5 eOp;
  private final NExp eExp;
  private final N$6 e$6;

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Decl(this);
    walker.caseStmt_Decl(this);
    walker.outStmt_Decl(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eType.apply(walker);
    this.eId.apply(walker);
    this.eOp.apply(walker);
    this.eExp.apply(walker);
    this.e$6.apply(walker);
  }

  NStmt_Decl(int line, int pos, NType pType, NId pId, N$5 pOp, NExp pExp, N$6 p$6) {
    this.line = line;
    this.pos = pos;
    this.eType = pType;
    this.eId = pId;
    this.eOp = pOp;
    this.eExp = pExp;
    this.e$6 = p$6;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Decl;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Decl;
  }

  public NType get_Type() {
    return this.eType;
  }

  public NId get_Id() {
    return this.eId;
  }

  public Token get_Op() {
    return this.eOp;
  }

  public NExp get_Exp() {
    return this.eExp;
  }

  NType internalGetType() {
    return this.eType;
  }

  NId internalGetId() {
    return this.eId;
  }

  N$5 internalGetOp() {
    return this.eOp;
  }

  NExp internalGetExp() {
    return this.eExp;
  }

  N$6 internalGet$6() {
    return this.e$6;
  }
}
