/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class NStmts_$1
    extends NStmts {

  private final int line;
  private final int pos;
  private final NStmts eStmts;
  private final NStmt eStmt;

  @Override
  public void apply(Walker walker) {
    walker.defaultIn(this);
    walker.defaultCase(this);
    walker.defaultOut(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eStmts.apply(walker);
    this.eStmt.apply(walker);
  }

  NStmts_$1(int line, int pos, NStmts pStmts, NStmt pStmt) {
    this.line = line;
    this.pos = pos;
    this.eStmts = pStmts;
    this.eStmt = pStmt;
  }

  @Override
  public Type getType() {
    return Type.TAnonymous;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmts;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmts_$1;
  }

  NStmts internalGetStmts() {
    return this.eStmts;
  }

  NStmt internalGetStmt() {
    return this.eStmt;
  }
}
