/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class NStmts_$2
    extends NStmts {

  private final int line;
  private final int pos;

  @Override
  public void apply(Walker walker) {
    walker.defaultIn(this);
    walker.defaultCase(this);
    walker.defaultOut(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
  }

  public NStmts_$2(int line, int pos) {
    this.line = line;
    this.pos = pos;
  }

  @Override
  public Type getType() {
    return Type.TAnonymous;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmts;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmts_$2;
  }
}
