/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NTerm_True
    extends NTerm {

  private final int line;
  private final int pos;
  private final N$26 eKeyword;

  @Override
  public void apply(Walker walker) {
    walker.inTerm_True(this);
    walker.caseTerm_True(this);
    walker.outTerm_True(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eKeyword.apply(walker);
  }

  NTerm_True(int line, int pos, N$26 pKeyword) {
    this.line = line;
    this.pos = pos;
    this.eKeyword = pKeyword;
  }

  @Override
  public Type getType() {
    return Type.T_Term_True;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Term;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Term_True;
  }

  public Token get_Keyword() {
    return this.eKeyword;
  }

  N$26 internalGetKeyword() {
    return this.eKeyword;
  }
}
