/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NTerm_ArrayRef
    extends NTerm {

  private final int line;
  private final int pos;
  private final NId eId;
  private final N$7 eLBracket;
  private final NExp eExp;
  private final N$8 e$8;

  @Override
  public void apply(Walker walker) {
    walker.inTerm_ArrayRef(this);
    walker.caseTerm_ArrayRef(this);
    walker.outTerm_ArrayRef(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eId.apply(walker);
    this.eLBracket.apply(walker);
    this.eExp.apply(walker);
    this.e$8.apply(walker);
  }

  NTerm_ArrayRef(int line, int pos, NId pId, N$7 pLBracket, NExp pExp, N$8 p$8) {
    this.line = line;
    this.pos = pos;
    this.eId = pId;
    this.eLBracket = pLBracket;
    this.eExp = pExp;
    this.e$8 = p$8;
  }

  @Override
  public Type getType() {
    return Type.T_Term_ArrayRef;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Term;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Term_ArrayRef;
  }

  public NId get_Id() {
    return this.eId;
  }

  public Token get_LBracket() {
    return this.eLBracket;
  }

  public NExp get_Exp() {
    return this.eExp;
  }

  NId internalGetId() {
    return this.eId;
  }

  N$7 internalGetLBracket() {
    return this.eLBracket;
  }

  NExp internalGetExp() {
    return this.eExp;
  }

  N$8 internalGet$8() {
    return this.e$8;
  }
}
