/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NTerm_ArraySize
    extends NTerm {

  private final int line;
  private final int pos;
  private final N$29 eKeyword;
  private final N$0 eLPar;
  private final NId eId;
  private final N$1 e$1;

  @Override
  public void apply(Walker walker) {
    walker.inTerm_ArraySize(this);
    walker.caseTerm_ArraySize(this);
    walker.outTerm_ArraySize(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eKeyword.apply(walker);
    this.eLPar.apply(walker);
    this.eId.apply(walker);
    this.e$1.apply(walker);
  }

  NTerm_ArraySize(int line, int pos, N$29 pKeyword, N$0 pLPar, NId pId, N$1 p$1) {
    this.line = line;
    this.pos = pos;
    this.eKeyword = pKeyword;
    this.eLPar = pLPar;
    this.eId = pId;
    this.e$1 = p$1;
  }

  @Override
  public Type getType() {
    return Type.T_Term_ArraySize;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Term;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Term_ArraySize;
  }

  public Token get_Keyword() {
    return this.eKeyword;
  }

  public Token get_LPar() {
    return this.eLPar;
  }

  public NId get_Id() {
    return this.eId;
  }

  N$29 internalGetKeyword() {
    return this.eKeyword;
  }

  N$0 internalGetLPar() {
    return this.eLPar;
  }

  NId internalGetId() {
    return this.eId;
  }

  N$1 internalGet$1() {
    return this.e$1;
  }
}
