/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NTerm_Num
    extends NTerm {

  private final int line;
  private final int pos;
  private final NNum eNum;

  @Override
  public void apply(Walker walker) {
    walker.inTerm_Num(this);
    walker.caseTerm_Num(this);
    walker.outTerm_Num(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eNum.apply(walker);
  }

  public NTerm_Num(int line, int pos, NNum pNum) {
    this.line = line;
    this.pos = pos;
    this.eNum = pNum;
  }

  @Override
  public Type getType() {
    return Type.T_Term_Num;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Term;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Term_Num;
  }

  public NNum get_Num() {
    return this.eNum;
  }

  NNum internalGetNum() {
    return this.eNum;
  }
}
