/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NType_Void
    extends NType {

  private final int line;
  private final int pos;
  private final N$18 eKeyword;

  @Override
  public void apply(Walker walker) {
    walker.inType_Void(this);
    walker.caseType_Void(this);
    walker.outType_Void(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eKeyword.apply(walker);
  }

  NType_Void(int line, int pos, N$18 pKeyword) {
    this.line = line;
    this.pos = pos;
    this.eKeyword = pKeyword;
  }

  @Override
  public Type getType() {
    return Type.T_Type_Void;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Type;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Type_Void;
  }

  public Token get_Keyword() {
    return this.eKeyword;
  }

  N$18 internalGetKeyword() {
    return this.eKeyword;
  }
}
