/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NType_Bool
    extends NType {

  private final int line;
  private final int pos;
  private final N$16 eKeyword;

  @Override
  public void apply(Walker walker) {
    walker.inType_Bool(this);
    walker.caseType_Bool(this);
    walker.outType_Bool(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eKeyword.apply(walker);
  }

  NType_Bool(int line, int pos, N$16 pKeyword) {
    this.line = line;
    this.pos = pos;
    this.eKeyword = pKeyword;
  }

  @Override
  public Type getType() {
    return Type.T_Type_Bool;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Type;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Type_Bool;
  }

  public Token get_Keyword() {
    return this.eKeyword;
  }

  N$16 internalGetKeyword() {
    return this.eKeyword;
  }
}
