/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public class NType_Int
    extends NType {

  private final int line;
  private final int pos;
  private final N$15 eKeyword;

  @Override
  public void apply(Walker walker) {
    walker.inType_Int(this);
    walker.caseType_Int(this);
    walker.outType_Int(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eKeyword.apply(walker);
  }

  NType_Int(int line, int pos, N$15 pKeyword) {
    this.line = line;
    this.pos = pos;
    this.eKeyword = pKeyword;
  }

  @Override
  public Type getType() {
    return Type.T_Type_Int;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Type;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Type_Int;
  }

  public Token get_Keyword() {
    return this.eKeyword;
  }

  N$15 internalGetKeyword() {
    return this.eKeyword;
  }
}
