/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class S_0
    extends TransitionState {

  static final S_0 instance = new S_0();

  private S_0() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol_9:
      return S_1.instance;
    case Symbol_32:
      return S_1.instance;
    case Symbol_34:
      return S_2.instance;
    case Symbol_37:
      return S_3.instance;
    case Symbol_40:
      return S_4.instance;
    case Symbol_41:
      return S_5.instance;
    case Symbol_42:
      return S_6.instance;
    case Symbol_43:
      return S_7.instance;
    case Symbol_44:
      return S_8.instance;
    case Symbol_45:
      return S_9.instance;
    case Symbol_47:
      return S_10.instance;
    case Symbol__0:
      return S_11.instance;
    case Symbol_59:
      return S_12.instance;
    case Symbol_60:
      return S_13.instance;
    case Symbol_61:
      return S_14.instance;
    case Symbol_91:
      return S_15.instance;
    case Symbol_93:
      return S_16.instance;
    case Symbol__a:
      return S_17.instance;
    case Symbol__b:
      return S_18.instance;
    case Symbol__c:
      return S_17.instance;
    case Symbol__d:
      return S_17.instance;
    case Symbol__e:
      return S_19.instance;
    case Symbol__f:
      return S_20.instance;
    case Symbol__g:
      return S_17.instance;
    case Symbol__h:
      return S_17.instance;
    case Symbol__i:
      return S_21.instance;
    case Symbol__l:
      return S_17.instance;
    case Symbol__n:
      return S_22.instance;
    case Symbol__o:
      return S_17.instance;
    case Symbol__p:
      return S_23.instance;
    case Symbol__r:
      return S_24.instance;
    case Symbol__s:
      return S_25.instance;
    case Symbol__t:
      return S_26.instance;
    case Symbol__u:
      return S_17.instance;
    case Symbol__v:
      return S_27.instance;
    case Symbol__w:
      return S_28.instance;
    case Symbol__z:
      return S_17.instance;
    case Symbol_123:
      return S_29.instance;
    case Symbol_125:
      return S_30.instance;
    default:
      return null;
    }
  }

}
