/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class S_16
    extends FinalState {

  static final S_16 instance = new S_16();

  private S_16() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$8(text, line, pos);
  }
}
