/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class S_31
    extends FinalState {

  static final S_31 instance = new S_31();

  private S_31() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return null;
  }
}
