/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class S_34
    extends TransitionState {

  static final S_34 instance = new S_34();

  private S_34() {
  }

  void setMarker(Lexer lexer) {
    lexer.setMarker0();
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol_min:
      return S_52.instance;
    case Symbol_9:
      return S_52.instance;
    case Symbol_32:
      return S_52.instance;
    case Symbol_33:
      return S_52.instance;
    case Symbol_34:
      return S_52.instance;
    case Symbol_37:
      return S_52.instance;
    case Symbol_40:
      return S_52.instance;
    case Symbol_41:
      return S_52.instance;
    case Symbol_42:
      return S_53.instance;
    case Symbol_43:
      return S_52.instance;
    case Symbol_44:
      return S_52.instance;
    case Symbol_45:
      return S_52.instance;
    case Symbol_47:
      return S_52.instance;
    case Symbol__0:
      return S_52.instance;
    case Symbol_59:
      return S_52.instance;
    case Symbol_60:
      return S_52.instance;
    case Symbol_61:
      return S_52.instance;
    case Symbol_91:
      return S_52.instance;
    case Symbol_93:
      return S_52.instance;
    case Symbol__a:
      return S_52.instance;
    case Symbol__b:
      return S_52.instance;
    case Symbol__c:
      return S_52.instance;
    case Symbol__d:
      return S_52.instance;
    case Symbol__e:
      return S_52.instance;
    case Symbol__f:
      return S_52.instance;
    case Symbol__g:
      return S_52.instance;
    case Symbol__h:
      return S_52.instance;
    case Symbol__i:
      return S_52.instance;
    case Symbol__l:
      return S_52.instance;
    case Symbol__n:
      return S_52.instance;
    case Symbol__o:
      return S_52.instance;
    case Symbol__p:
      return S_52.instance;
    case Symbol__r:
      return S_52.instance;
    case Symbol__s:
      return S_52.instance;
    case Symbol__t:
      return S_52.instance;
    case Symbol__u:
      return S_52.instance;
    case Symbol__v:
      return S_52.instance;
    case Symbol__w:
      return S_52.instance;
    case Symbol__z:
      return S_52.instance;
    case Symbol_123:
      return S_52.instance;
    case Symbol_125:
      return S_52.instance;
    case Symbol_end:
      return S_54.instance;
    default:
      return null;
    }
  }

}
