/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class S_36
    extends FinalState {

  static final S_36 instance = new S_36();

  private S_36() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$5(text, line, pos);
  }
}
