/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class S_37
    extends FinalState {

  static final S_37 instance = new S_37();

  private S_37() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$19(text, line, pos);
  }
}
