/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class S_38
    extends FinalState {

  static final S_38 instance = new S_38();

  private S_38() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new NId(text, line, pos);
  }
}
