/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class S_54
    extends FinalState {

  static final S_54 instance = new S_54();

  private S_54() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.acceptWithMarker0(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$24(text, line, pos);
  }
}
