/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class S_68
    extends FinalState {

  static final S_68 instance = new S_68();

  private S_68() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return null;
  }
}
