/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

class S_8
    extends FinalState {

  static final S_8 instance = new S_8();

  private S_8() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$2(text, line, pos);
  }
}
