/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

enum Symbol {
  Symbol_min,
  Symbol_9,
  Symbol_32,
  Symbol_33,
  Symbol_34,
  Symbol_37,
  Symbol_40,
  Symbol_41,
  Symbol_42,
  Symbol_43,
  Symbol_44,
  Symbol_45,
  Symbol_47,
  Symbol__0,
  Symbol_59,
  Symbol_60,
  Symbol_61,
  Symbol_91,
  Symbol_93,
  Symbol__a,
  Symbol__b,
  Symbol__c,
  Symbol__d,
  Symbol__e,
  Symbol__f,
  Symbol__g,
  Symbol__h,
  Symbol__i,
  Symbol__l,
  Symbol__n,
  Symbol__o,
  Symbol__p,
  Symbol__r,
  Symbol__s,
  Symbol__t,
  Symbol__u,
  Symbol__v,
  Symbol__w,
  Symbol__z,
  Symbol_123,
  Symbol_125,
  Symbol_end;

  static Symbol getSymbol(char c) {
    switch(c) {
    case 13: return Symbol_9;
    case 32: return Symbol_32;
    case 33: return Symbol_33;
    case 34: return Symbol_34;
    case 37: return Symbol_37;
    case 40: return Symbol_40;
    case 41: return Symbol_41;
    case 42: return Symbol_42;
    case 43: return Symbol_43;
    case 44: return Symbol_44;
    case 45: return Symbol_45;
    case 46: return Symbol_33;
    case 47: return Symbol_47;
    case 58: return Symbol_33;
    case 59: return Symbol_59;
    case 60: return Symbol_60;
    case 61: return Symbol_61;
    case 91: return Symbol_91;
    case 92: return Symbol_33;
    case 93: return Symbol_93;
    case 97: return Symbol__a;
    case 98: return Symbol__b;
    case 99: return Symbol__c;
    case 100: return Symbol__d;
    case 101: return Symbol__e;
    case 102: return Symbol__f;
    case 103: return Symbol__g;
    case 104: return Symbol__h;
    case 105: return Symbol__i;
    case 108: return Symbol__l;
    case 109: return Symbol__c;
    case 110: return Symbol__n;
    case 111: return Symbol__o;
    case 112: return Symbol__p;
    case 113: return Symbol__c;
    case 114: return Symbol__r;
    case 115: return Symbol__s;
    case 116: return Symbol__t;
    case 117: return Symbol__u;
    case 118: return Symbol__v;
    case 119: return Symbol__w;
    case 122: return Symbol__z;
    case 123: return Symbol_123;
    case 124: return Symbol_33;
    case 125: return Symbol_125;
    case 126: return Symbol_33;
    default:
      if(c <= 8) {
        return Symbol_min;
      }
      if(c >= 127) {
        return Symbol_min;
      }
      if(c >= 9 && c <= 10) {
        return Symbol_9;
      }
      if(c >= 11 && c <= 12) {
        return Symbol_min;
      }
      if(c >= 14 && c <= 31) {
        return Symbol_min;
      }
      if(c >= 35 && c <= 36) {
        return Symbol_33;
      }
      if(c >= 38 && c <= 39) {
        return Symbol_33;
      }
      if(c >= 48 && c <= 57) {
        return Symbol__0;
      }
      if(c >= 62 && c <= 90) {
        return Symbol_33;
      }
      if(c >= 94 && c <= 96) {
        return Symbol_33;
      }
      if(c >= 106 && c <= 107) {
        return Symbol__c;
      }
      if(c >= 120 && c <= 121) {
        return Symbol__c;
      }
    }

    return null;
  }
}
