/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

import java.io.*;
public class Test {

  public static void main(String[] args)
    throws Exception {

    Reader in;

    if(args.length > 0) {
      in = new FileReader(args[0]);
    }
    else {
      in = new InputStreamReader(System.in);
    }

    Node syntaxTree = new Parser(in).parse();
    System.out.println();
    syntaxTree.apply(new Walker() {
      @Override
      public void defaultOut(Node node) {
        if(node instanceof Token) {
          Token token = (Token) node;
          System.out.println(token.getType() + ":\"" + token.getText() + "\"@(" + token.getLine() + "," + token.getPos() + ")");
        }
      }
    });
  }
}
