/* This file was generated by SableCC ( http://sablecc.org ). */

package tp2;

public abstract class Token
    extends Node {

  private final String text;
  private final int line;
  private final int pos;

  public Token(String text, int line, int pos) {
    this.text = text;
    this.line = line;
    this.pos = pos;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.TNotAProduction;
  }

  public String getText() {
    return this.text;
  }

  public int getLine() {
    return this.line;
  }

  public int getPos() {
    return this.pos;
  }

  @Override
  public String toString() {
    return "\"" + getText() + "\"@(" + getLine() + "," + getPos() + ")";
  }

  @Override
  public void apply(Walker walker) {
    walker.defaultIn(this);
    walker.defaultCase(this);
    walker.defaultOut(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
  }
}
