/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.node;

import org.sablecc.sablecc.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TEmptyKeyword extends Token
{
    public TEmptyKeyword()
    {
        super.setText("Empty");
    }

    public TEmptyKeyword(int line, int pos)
    {
        super.setText("Empty");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEmptyKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEmptyKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEmptyKeyword text.");
    }
}
